fix: remove winget configuration (#28)
* fix: homebrew binary version

* fix: manual bump

* fix: winget

* fix: winget

* feat: remove winget because of   ⨯ release failed after 3m57s
    error=
    │ 1 error occurred:
    │ 	* winget: could not create ref "refs/heads/kubectl-nuke-0.5.3" from "d3d8933f1ab29de90f692cc2b8b06608672b152f": POST https://api.github.com/repos/microsoft/winget-pkgs/git/refs: 404 Not Found []
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.10.2/x64/goreleaser' failed with exit code 1